<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HaNews', 'doctrine');

/**
 * BaseHaNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $news_einsteller
 * @property string $news_title
 * @property clob $news_text
 * @property timestamp $publish_date
 * @property string $image
 * @property integer $status
 * 
 * @method string    getNewsEinsteller()  Returns the current record's "news_einsteller" value
 * @method string    getNewsTitle()       Returns the current record's "news_title" value
 * @method clob      getNewsText()        Returns the current record's "news_text" value
 * @method timestamp getPublishDate()     Returns the current record's "publish_date" value
 * @method string    getImage()           Returns the current record's "image" value
 * @method integer   getStatus()          Returns the current record's "status" value
 * @method HaNews    setNewsEinsteller()  Sets the current record's "news_einsteller" value
 * @method HaNews    setNewsTitle()       Sets the current record's "news_title" value
 * @method HaNews    setNewsText()        Sets the current record's "news_text" value
 * @method HaNews    setPublishDate()     Sets the current record's "publish_date" value
 * @method HaNews    setImage()           Sets the current record's "image" value
 * @method HaNews    setStatus()          Sets the current record's "status" value
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHaNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ha_news');
        $this->hasColumn('news_einsteller', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('news_title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('news_text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('publish_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $signable0 = new Doctrine_Template_Signable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $taggable0 = new Taggable();
        $this->actAs($signable0);
        $this->actAs($timestampable0);
        $this->actAs($taggable0);
    }
}