<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dokument', 'doctrine');

/**
 * BaseDokument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $archiv_id
 * @property string $bestand_sig
 * @property string $signatur
 * @property integer $verzeichnungseinheit_id
 * @property string $titel
 * @property string $beschreibung
 * @property string $filename
 * @property string $datierung
 * @property integer $date_day
 * @property integer $date_month
 * @property integer $date_year
 * @property integer $position
 * @property integer $vorlagentyp_id
 * @property string $kommentar
 * @property string $folio
 * @property string $copyright
 * @property string $einsteller
 * @property integer $status
 * @property integer $usergenerated
 * @property string $user_description
 * @property integer $validated
 * @property Verzeichnungseinheit $Verzeichnungseinheit
 * @property Vorlagentyp $Vorlagentyp
 * @property Doctrine_Collection $MyDokumente
 * 
 * @method integer              getArchivId()                Returns the current record's "archiv_id" value
 * @method string               getBestandSig()              Returns the current record's "bestand_sig" value
 * @method string               getSignatur()                Returns the current record's "signatur" value
 * @method integer              getVerzeichnungseinheitId()  Returns the current record's "verzeichnungseinheit_id" value
 * @method string               getTitel()                   Returns the current record's "titel" value
 * @method string               getBeschreibung()            Returns the current record's "beschreibung" value
 * @method string               getFilename()                Returns the current record's "filename" value
 * @method string               getDatierung()               Returns the current record's "datierung" value
 * @method integer              getDateDay()                 Returns the current record's "date_day" value
 * @method integer              getDateMonth()               Returns the current record's "date_month" value
 * @method integer              getDateYear()                Returns the current record's "date_year" value
 * @method integer              getPosition()                Returns the current record's "position" value
 * @method integer              getVorlagentypId()           Returns the current record's "vorlagentyp_id" value
 * @method string               getKommentar()               Returns the current record's "kommentar" value
 * @method string               getFolio()                   Returns the current record's "folio" value
 * @method string               getCopyright()               Returns the current record's "copyright" value
 * @method string               getEinsteller()              Returns the current record's "einsteller" value
 * @method integer              getStatus()                  Returns the current record's "status" value
 * @method integer              getUsergenerated()           Returns the current record's "usergenerated" value
 * @method string               getUserDescription()         Returns the current record's "user_description" value
 * @method integer              getValidated()               Returns the current record's "validated" value
 * @method Verzeichnungseinheit getVerzeichnungseinheit()    Returns the current record's "Verzeichnungseinheit" value
 * @method Vorlagentyp          getVorlagentyp()             Returns the current record's "Vorlagentyp" value
 * @method Doctrine_Collection  getMyDokumente()             Returns the current record's "MyDokumente" collection
 * @method Dokument             setArchivId()                Sets the current record's "archiv_id" value
 * @method Dokument             setBestandSig()              Sets the current record's "bestand_sig" value
 * @method Dokument             setSignatur()                Sets the current record's "signatur" value
 * @method Dokument             setVerzeichnungseinheitId()  Sets the current record's "verzeichnungseinheit_id" value
 * @method Dokument             setTitel()                   Sets the current record's "titel" value
 * @method Dokument             setBeschreibung()            Sets the current record's "beschreibung" value
 * @method Dokument             setFilename()                Sets the current record's "filename" value
 * @method Dokument             setDatierung()               Sets the current record's "datierung" value
 * @method Dokument             setDateDay()                 Sets the current record's "date_day" value
 * @method Dokument             setDateMonth()               Sets the current record's "date_month" value
 * @method Dokument             setDateYear()                Sets the current record's "date_year" value
 * @method Dokument             setPosition()                Sets the current record's "position" value
 * @method Dokument             setVorlagentypId()           Sets the current record's "vorlagentyp_id" value
 * @method Dokument             setKommentar()               Sets the current record's "kommentar" value
 * @method Dokument             setFolio()                   Sets the current record's "folio" value
 * @method Dokument             setCopyright()               Sets the current record's "copyright" value
 * @method Dokument             setEinsteller()              Sets the current record's "einsteller" value
 * @method Dokument             setStatus()                  Sets the current record's "status" value
 * @method Dokument             setUsergenerated()           Sets the current record's "usergenerated" value
 * @method Dokument             setUserDescription()         Sets the current record's "user_description" value
 * @method Dokument             setValidated()               Sets the current record's "validated" value
 * @method Dokument             setVerzeichnungseinheit()    Sets the current record's "Verzeichnungseinheit" value
 * @method Dokument             setVorlagentyp()             Sets the current record's "Vorlagentyp" value
 * @method Dokument             setMyDokumente()             Sets the current record's "MyDokumente" collection
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDokument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dokument');
        $this->hasColumn('archiv_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('bestand_sig', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
        $this->hasColumn('signatur', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
        $this->hasColumn('verzeichnungseinheit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('titel', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('beschreibung', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('datierung', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_day', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('date_month', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('date_year', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('vorlagentyp_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('kommentar', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('folio', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('copyright', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('einsteller', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('usergenerated', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('user_description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('validated', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Verzeichnungseinheit', array(
             'local' => 'verzeichnungseinheit_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Vorlagentyp', array(
             'local' => 'vorlagentyp_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasMany('MyDokumente', array(
             'local' => 'id',
             'foreign' => 'dokument_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'verzeichnungseinheit_id',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($sortable0);
    }
}