<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vorlagentyp', 'doctrine');

/**
 * BaseVorlagentyp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $Dokument
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getCode()     Returns the current record's "code" value
 * @method Doctrine_Collection getDokument() Returns the current record's "Dokument" collection
 * @method Vorlagentyp         setName()     Sets the current record's "name" value
 * @method Vorlagentyp         setCode()     Sets the current record's "code" value
 * @method Vorlagentyp         setDokument() Sets the current record's "Dokument" collection
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVorlagentyp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vorlagentyp');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dokument', array(
             'local' => 'id',
             'foreign' => 'vorlagentyp_id'));
    }
}