<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Verweis', 'doctrine');

/**
 * BaseVerweis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $archiv_id
 * @property string $bestand_sig
 * @property string $laufzeit
 * @property string $beschreibung
 * @property string $titel
 * @property string $sperrvermerk
 * @property string $bestellsig
 * @property string $archivgutart
 * @property string $altsig
 * @property string $umfang
 * @property string $bem
 * @property integer $status
 * 
 * @method integer getArchivId()     Returns the current record's "archiv_id" value
 * @method string  getBestandSig()   Returns the current record's "bestand_sig" value
 * @method string  getLaufzeit()     Returns the current record's "laufzeit" value
 * @method string  getBeschreibung() Returns the current record's "beschreibung" value
 * @method string  getTitel()        Returns the current record's "titel" value
 * @method string  getSperrvermerk() Returns the current record's "sperrvermerk" value
 * @method string  getBestellsig()   Returns the current record's "bestellsig" value
 * @method string  getArchivgutart() Returns the current record's "archivgutart" value
 * @method string  getAltsig()       Returns the current record's "altsig" value
 * @method string  getUmfang()       Returns the current record's "umfang" value
 * @method string  getBem()          Returns the current record's "bem" value
 * @method integer getStatus()       Returns the current record's "status" value
 * @method Verweis setArchivId()     Sets the current record's "archiv_id" value
 * @method Verweis setBestandSig()   Sets the current record's "bestand_sig" value
 * @method Verweis setLaufzeit()     Sets the current record's "laufzeit" value
 * @method Verweis setBeschreibung() Sets the current record's "beschreibung" value
 * @method Verweis setTitel()        Sets the current record's "titel" value
 * @method Verweis setSperrvermerk() Sets the current record's "sperrvermerk" value
 * @method Verweis setBestellsig()   Sets the current record's "bestellsig" value
 * @method Verweis setArchivgutart() Sets the current record's "archivgutart" value
 * @method Verweis setAltsig()       Sets the current record's "altsig" value
 * @method Verweis setUmfang()       Sets the current record's "umfang" value
 * @method Verweis setBem()          Sets the current record's "bem" value
 * @method Verweis setStatus()       Sets the current record's "status" value
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVerweis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('verweis');
        $this->hasColumn('archiv_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('bestand_sig', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 63,
             ));
        $this->hasColumn('laufzeit', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
        $this->hasColumn('beschreibung', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('titel', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('sperrvermerk', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bestellsig', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('archivgutart', 'string', 63, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 63,
             ));
        $this->hasColumn('altsig', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('umfang', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bem', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'notnull' => true,
             'length' => 1,
             ));


        $this->index('vz_archivindex', array(
             'fields' => 
             array(
              0 => 'archiv_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $signable0 = new Doctrine_Template_Signable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($signable0);
        $this->actAs($timestampable0);
    }
}