<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vorgang', 'doctrine');

/**
 * BaseVorgang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $bestand_sig
 * @property string $ve_signatur
 * @property string $laufzeit
 * @property string $titel
 * @property string $bestellsig
 * @property string $umfang
 * @property string $archivgutart
 * @property integer $status
 * 
 * @method string  getBestandSig()   Returns the current record's "bestand_sig" value
 * @method string  getVeSignatur()   Returns the current record's "ve_signatur" value
 * @method string  getLaufzeit()     Returns the current record's "laufzeit" value
 * @method string  getTitel()        Returns the current record's "titel" value
 * @method string  getBestellsig()   Returns the current record's "bestellsig" value
 * @method string  getUmfang()       Returns the current record's "umfang" value
 * @method string  getArchivgutart() Returns the current record's "archivgutart" value
 * @method integer getStatus()       Returns the current record's "status" value
 * @method Vorgang setBestandSig()   Sets the current record's "bestand_sig" value
 * @method Vorgang setVeSignatur()   Sets the current record's "ve_signatur" value
 * @method Vorgang setLaufzeit()     Sets the current record's "laufzeit" value
 * @method Vorgang setTitel()        Sets the current record's "titel" value
 * @method Vorgang setBestellsig()   Sets the current record's "bestellsig" value
 * @method Vorgang setUmfang()       Sets the current record's "umfang" value
 * @method Vorgang setArchivgutart() Sets the current record's "archivgutart" value
 * @method Vorgang setStatus()       Sets the current record's "status" value
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVorgang extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vorgang');
        $this->hasColumn('bestand_sig', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 63,
             ));
        $this->hasColumn('ve_signatur', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 63,
             ));
        $this->hasColumn('laufzeit', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
        $this->hasColumn('titel', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('bestellsig', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('umfang', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('archivgutart', 'string', 63, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 63,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $signable0 = new Doctrine_Template_Signable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($signable0);
        $this->actAs($timestampable0);
    }
}