<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HaFaq', 'doctrine');

/**
 * BaseHaFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $question
 * @property string $answer
 * @property integer $pos
 * 
 * @method string  getQuestion() Returns the current record's "question" value
 * @method string  getAnswer()   Returns the current record's "answer" value
 * @method integer getPos()      Returns the current record's "pos" value
 * @method HaFaq   setQuestion() Sets the current record's "question" value
 * @method HaFaq   setAnswer()   Sets the current record's "answer" value
 * @method HaFaq   setPos()      Sets the current record's "pos" value
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHaFaq extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ha_faq');
        $this->hasColumn('question', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 512,
             ));
        $this->hasColumn('answer', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('pos', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}