<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Patenobjekt', 'doctrine');

/**
 * BasePatenobjekt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type
 * @property string $titel
 * @property string $beschreibung
 * @property string $inhalt
 * @property string $zustand
 * @property string $restaurierung
 * @property string $massnahmen
 * @property integer $status
 * @property boolean $verfuegbar
 * @property string $tekt_nr
 * @property string $bestand_sig
 * @property string $ve_signatur
 * @property Doctrine_Collection $PatenobjektPhotos
 * 
 * @method integer             getType()              Returns the current record's "type" value
 * @method string              getTitel()             Returns the current record's "titel" value
 * @method string              getBeschreibung()      Returns the current record's "beschreibung" value
 * @method string              getInhalt()            Returns the current record's "inhalt" value
 * @method string              getZustand()           Returns the current record's "zustand" value
 * @method string              getRestaurierung()     Returns the current record's "restaurierung" value
 * @method string              getMassnahmen()        Returns the current record's "massnahmen" value
 * @method integer             getStatus()            Returns the current record's "status" value
 * @method boolean             getVerfuegbar()        Returns the current record's "verfuegbar" value
 * @method string              getTektNr()            Returns the current record's "tekt_nr" value
 * @method string              getBestandSig()        Returns the current record's "bestand_sig" value
 * @method string              getVeSignatur()        Returns the current record's "ve_signatur" value
 * @method Doctrine_Collection getPatenobjektPhotos() Returns the current record's "PatenobjektPhotos" collection
 * @method Patenobjekt         setType()              Sets the current record's "type" value
 * @method Patenobjekt         setTitel()             Sets the current record's "titel" value
 * @method Patenobjekt         setBeschreibung()      Sets the current record's "beschreibung" value
 * @method Patenobjekt         setInhalt()            Sets the current record's "inhalt" value
 * @method Patenobjekt         setZustand()           Sets the current record's "zustand" value
 * @method Patenobjekt         setRestaurierung()     Sets the current record's "restaurierung" value
 * @method Patenobjekt         setMassnahmen()        Sets the current record's "massnahmen" value
 * @method Patenobjekt         setStatus()            Sets the current record's "status" value
 * @method Patenobjekt         setVerfuegbar()        Sets the current record's "verfuegbar" value
 * @method Patenobjekt         setTektNr()            Sets the current record's "tekt_nr" value
 * @method Patenobjekt         setBestandSig()        Sets the current record's "bestand_sig" value
 * @method Patenobjekt         setVeSignatur()        Sets the current record's "ve_signatur" value
 * @method Patenobjekt         setPatenobjektPhotos() Sets the current record's "PatenobjektPhotos" collection
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatenobjekt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patenobjekt');
        $this->hasColumn('type', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('titel', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('beschreibung', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('inhalt', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('zustand', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('restaurierung', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('massnahmen', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('verfuegbar', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('tekt_nr', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('bestand_sig', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
        $this->hasColumn('ve_signatur', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PatenobjektPhoto as PatenobjektPhotos', array(
             'local' => 'id',
             'foreign' => 'patenobjekt_id'));

        $signable0 = new Doctrine_Template_Signable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($signable0);
        $this->actAs($timestampable0);
    }
}