<?php

/**
 * Bestand
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer
 */
class Bestand extends BaseBestand
{
    
    public function getSignaturSlug() {
        return str_replace(array('/',':',"\r", "\t", "\n"), '~', $this->getBestandSig() .'+'. substr($this->getBestandsname(), 0, 50));
    }

}
