<?php

/**
 * BestandTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BestandTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object BestandTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Bestand');
  }

}