<?php

/**
 * CmsInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsInfo');
    }
}