<?php

/**
 * CmsSlider
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Maik Mettenheimer <mettenheimer@pausanio.de>
 */
class CmsSlider extends BaseCmsSlider
{

    /**
     * Overwrite save method
     *
     * @param Doctrine_Connection $conn
     * @return mixed
     */
    public function save(Doctrine_Connection $conn = null)
    {
        if ($this->isModified() || $this->isNew()) {
            $this->resizeImage();
            $pos = $this->getPosition();
            if(empty($pos)){
                $this->setPosition($this->getFinalPosition()+1);
            }
        }
        return parent::save($conn);
    }

    /**
     * Resize image
     *
     * @return boolean
     */
    protected function resizeImage()
    {
        $filename = substr($this->getImage(), 0, strrpos($this->getImage(), '.')) . '.jpg';
        $sourceFile = sfConfig::get('app_cms_slider_imagefile_org') . $this->getImage();
        if ($this->getImage()) {
            $picture = new sfThumbnail(sfConfig::get('app_cms_slider_image_maxwidth'), sfConfig::get('app_cms_slider_image_maxheight'), true, true, sfConfig::get('app_cms_image_quality'));
            $picture->loadFile($sourceFile);
            $picture->save(sfConfig::get('app_cms_slider_imagefile') . $filename, 'image/jpeg');
        }
        return true;
    }

    /**
     * Image source
     *
     * @return string
     */
    protected function getImageSrc()
    {
        return sfConfig::get('app_cms_slider_image') . substr($this->getImage(), 0, strrpos($this->getImage(), '.')) . '.jpg';
    }

}
