<?php

/**
 * CmsSliderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsSliderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsSliderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsSlider');
    }
}