<?php

/**
 * CmsTextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsTextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsTextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsText');
    }
}