<?php

/**
 * CmsText
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Norman Fiedler
 */
class CmsText extends BaseCmsText
{

  public static function getTextByLanguage($module)
  {
    $q = Doctrine_Core::getTable('CmsText')
        ->createQuery()
        ->where('module = ?', $module);
    $return = array();
    foreach ($q->execute() as $i => $t) {
      $return[$t->getName()]['de'] = $t->getText();
    }
    return $return;
  }

  public function getTextSubstr()
  {
    return substr(strip_tags($this->getText()), 0, 60);
  }

  public function getEditors()
  {
    return $this->getCreatedBy();
  }

}
