<?php

/**
 * DokumentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DokumentTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object DokumentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Dokument');
  }

  public function retrieveBackendDokumentList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->andWhere('usergenerated = ?', 1);
    return $q;
  }

  public static function countDokuments($createdBy = false){
      $q = Doctrine_Core::getTable('Dokument')
                            ->createQuery()
                            ->select('count(id)');
      if($createdBy){
          $q->where('created_by = ?', $createdBy);
      }
      $res = $q->fetchArray();
      return $res[0]['count'];
  }

}