<?php

/**
 * HaFaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HaFaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HaFaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HaFaq');
    }
}