<?php

/**
 * HaNewsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HaNewsTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object HaNewsTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('HaNews');
  }

}