<?php

/**
 * HaProjekttypenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HaProjekttypenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HaProjekttypenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HaProjekttypen');
    }
}