<?php

/**
 * HaProjekttypen
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Norman Fiedler
 */
class HaProjekttypen extends BaseHaProjekttypen
{

  public function __toString()
  {
    return $this->getName();
  }

}
