<?php

/**
 * HaProjekteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HaProjekteTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object HaProjekteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HaProjekte');
    }

    static public $status = array(
        '0' => 'In Vorbereitung',
        '1' => 'Laufend',
        '2' => 'Abgeschlossen'
    );

    public function getStatus()
    {
        return self::$status;
    }

    public static function countProjekte($createdBy = false){
        $q = self::getInstance()
            ->createQuery()
            ->select('count(id)');
        if($createdBy){
            $q->where('created_by = ?', $createdBy);
        }
        $res = $q->fetchArray();
        return $res[0]['count'];
    }

}