<?php

/**
 * HaProjekte
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Norman Fiedler, Maik Mettenheimer <mettenheimer@pausanio.de>
 */
class HaProjekte extends BaseHaProjekte
{

  public static function getProjektData()
  {
    return Doctrine_Core::getTable('haProjekte')
            ->createQuery('p')
            ->select('p.*, u.email_address')
            ->from('haProjekte p')
            ->leftJoin('p.sfGuardUser u')
            ->where('p.status = ?', 1)
            ->orderBy('u.last_name, p.projekt_einsteller')
            ->execute();
  }

  public static function getProjektDataByID($id)
  {
    return Doctrine_Core::getTable('haProjekte')
            ->createQuery('p')
            ->select('p.*, u.email_address')
            ->from('haProjekte p')
            ->leftJoin('p.SfGuardUser u')
            ->where('p.id=?', $id)
            ->execute()->getFirst();
  }

  /**
   * Retrive Status name
   *
   * @param type $key
   * @return boolean
   */
  public function getStatusName($key = false)
  {
    if ($key === false) {
      return true;
    }
    $status = Doctrine_Core::getTable('HaProjekte')->getStatus();
    return $status[$key];
  }

}
