<?php

/**
 * MyArchivTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MyArchivTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MyArchivTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MyArchiv');
    }

    public static function findByUserAndId($userId, $Id){
        return self::getInstance()
            ->createQuery()
            ->where('created_by = ?', (int)$userId)
            ->andWhere('archiv_id = ?', (int)$Id)
            ->fetchOne();
    }
}