<?php

/**
 * MyDokumenteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MyDokumenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MyDokumenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MyDokumente');
    }

    public static function findByUserAndId($userId, $veId){
        return self::getInstance()
            ->createQuery()
            ->where('created_by = ?', (int)$userId)
            ->andWhere('dokument_id = ?', (int)$veId)
            ->fetchOne();
    }
}
