<?php

/**
 * VerweisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VerweisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VerweisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Verweis');
    }
}