<?php

/**
 * VorlagentypTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VorlagentypTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VorlagentypTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vorlagentyp');
    }
}