<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    historischesarchivkoeln.de
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {

    /**
     * Override save method in order to update the forum's user
     * 
     * @param   Doctrine_Connection $conn   optional connection parameter
     * @return  void
     */
    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        prestaForumFactory::getForumConnectorInstance()->synchUser($this->getId());
    }

    /**
     * Override delete method in order to update the forum's user
     * 
     * @param   Doctrine_Connection $conn   optional connection parameter
     * @return  void
     */
    public function delete(Doctrine_Connection $conn = null) {
        $userId = $this->getId();
        parent::delete($conn);
        prestaForumFactory::getForumConnectorInstance()->deleteForumUser($userId);
    }
    
    public function getCulture() {
        return 'de';
    }

}
