# Define all the models in your project that you want indexed.

DHASTK:
  models:
    Archiv:
      description: beschreibung
      title: signatur_title
      fields:
        id: unindexed
        signatur:
          boost: 1.5
          type: text
        name:
          boost: 1.5
          type: text
        beschreibung: text
        signatur_title: text
        signatur_slug: text
        user_description: unstored
        model: text
    Verzeichnungseinheit:
      description: beschreibung
      title: signatur_title
      fields:
        id: unindexed
        titel:
          boost: 1.5
          type: text
        beschreibung: text
        signatur_title: text
        signatur_slug: text
  index:
    encoding: UTF-8
    cultures: [de]
    analyzer: utf8num
    stop_words: ["aber","als","am","an","auch","auf","aus","bei","bin","bis","bist","da","dadurch","daher","darum","das","daß","dass","dein","deine","dem","den","der","des","dessen","deshalb","die","dies","dieser","dieses","doch","dort","du","durch","ein","eine","einem","einen","einer","eines","er","es","euer","eure","für","hatte","hatten","hattest","hattet","hier","hinter","ich","ihr","ihre","im","in","ist","ja","jede","jedem","jeden","jeder","jedes","jener","jenes","jetzt","kann","kannst","können","könnt","machen","mein","mein","mit","muß","mußt","musst","müssen","müßt","nach","nachdem","nein","nicht","nun","oder","seid","sein","seine","sich","sie","sind","soll","sollen","sollst","sollt","sonst","soweit","sowie","und","unser","unsere","unter","vom","von","vor","wann","warum","was","weiter","weitere","wenn","wer","werde","werden","werdet","weshalb","wie","wieder","wieso","wir","wird","wirst","wo","woher","wohin","zu","zum","zur","über"]