<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('bestand', 'user_description');
    }

    public function down()
    {
        $this->addColumn('bestand', 'user_description', 'string', '4000', array(
             ));
    }
}