<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('bestand', 'archivindex', array(
             'fields' => 
             array(
              0 => 'archiv_id',
             ),
             ));
        $this->addIndex('bestand', 'bestandsigindex', array(
             'fields' => 
             array(
              0 => 'bestand_sig',
             ),
             ));
        $this->addIndex('verzeichnungseinheit', 'vz_archivindex', array(
             'fields' => 
             array(
              0 => 'archiv_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('bestand', 'archivindex', array(
             'fields' => 
             array(
              0 => 'archiv_id',
             ),
             ));
        $this->removeIndex('bestand', 'bestandsigindex', array(
             'fields' => 
             array(
              0 => 'bestand_sig',
             ),
             ));
        $this->removeIndex('verzeichnungseinheit', 'vz_archivindex', array(
             'fields' => 
             array(
              0 => 'archiv_id',
             ),
             ));
    }
}